### PR TITLE
print path to bash and version before running tests.

### PR DESCRIPTION
**Pull request by rajiv**

### CODE REVIEW

**Comment by hannob** [comment]
Idea seems okay, however I find this a bit too verbose. Also it will print out the GPL message from bash which could give the impression that this is related to the script while the message belongs to bash.
Can you re-do it in a less verbose way? (output only path and version info) I may have time later to try myself.

**Comment by nogweii** [comment]
It could be as simple as piping the output to `head`:

``` bash
echo $(bash --version | head -n1)
```

**Comment by rajiv** [comment]
updated to print only the path and version.

**Comment by hannob** [comment]
I've now committed a different patch. It also adds the possibility to pass a different bash binary to the commandline which makes testing easier.
Also changed the color to one we don't use yet for other meanings.

**Comment by rajiv** [comment]
no longer needed after 5456137881d2b6f08336e49e76c6994524136970. thanks.

**Pull request closed without merging**
