### PR TITLE
SIG SEGFAULT silenced on line 18

### PR DESCRIPTION
**Pull request by thesp0nge**
Using { } around bash command, I silenced the SIGSEGFAULT message when received.

Just for sake of having a nicer output.

### CODE REVIEW

**Comment by hannob** [comment]
this will not only silence the check, it will also break it...

**Comment by thesp0nge** [comment]
Can you please elaborate more? I had double checked, the { } just trap the segmentation fault message. Just redirecting stderr on /dev/null doesn't work

**Comment by hannob** [comment]
if I run your version on a fully patched system it tells me I'm still vulnerable. I don't know why, maybe the surrounding brackets also change the error code.
Have you tested your patch both with a vulnerable and a non-vulnerable version?

**Comment by thesp0nge** [comment]
Just with a vulnerable bash. My fault, sorry.
I'll investigate further and improve my pull.

On 30 September 2014 09:08, Hanno Böck notifications@github.com wrote:

> if I run your version on a fully patched system it tells me I'm still
> vulnerable. I don't know why, maybe the surrounding brackets also change
> the error code.
> Have you tested your patch both with a vulnerable and a non-vulnerable
> version?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hannob/bashcheck/pull/9#issuecomment-57275219.

## 

$ cd /pub
$ more beer

Il primo blog di application security italiano morbido fuori e croccante
dentro: http://codiceinsicuro.it

**Pull request closed without merging**
